# Generated by Django 4.2.5 on 2023-10-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='individualusermodel',
            managers=[
            ],
        ),
    ]
