# Generated by Django 4.2.5 on 2023-10-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_user', '0002_alter_individualusermodel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualusermodel',
            name='second_phone_number_kk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='individualusermodel',
            name='second_phone_number_ru',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
