# Generated by Django 4.2.5 on 2023-10-08 03:25

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual_user', '0003_individualusermodel_second_phone_number_kk_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='individualusermodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
