# Generated by Django 4.2.5 on 2023-10-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual_user', '0004_alter_individualusermodel_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualusermodel',
            name='second_phone_number_kk',
        ),
        migrations.RemoveField(
            model_name='individualusermodel',
            name='second_phone_number_ru',
        ),
    ]
