# Generated by Django 4.2.5 on 2023-10-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_user', '0005_remove_individualusermodel_second_phone_number_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualusermodel',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='дополнительный номер телефона'),
        ),
    ]
