# Generated by Django 4.2.5 on 2023-10-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual_user', '0007_individualusermodel_loyalty'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='individualusermodel',
            managers=[
            ],
        ),
    ]
