# Generated by Django 4.2.5 on 2023-10-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0012_alter_loyaltymodel_discount_percentage'),
        ('individual_user', '0008_alter_individualusermodel_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualusermodel',
            name='loyalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.loyaltymodel', verbose_name='Уровень системы лояльности'),
        ),
    ]
