# Generated by Django 4.2.5 on 2023-10-10 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='DescriptionProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Компания производитель')),
                ('made_in', models.CharField(max_length=255, verbose_name='Страна изготовитель')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('package', models.CharField(max_length=255, verbose_name='Формат упаковки')),
            ],
            options={
                'verbose_name': 'Описание товара',
                'verbose_name_plural': 'Описания товаров',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categoryproductmodel')),
            ],
            options={
                'verbose_name': 'Подкатегория товара',
                'verbose_name_plural': 'Подкатегории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование товара')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='фото товара')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='стоимость за единицу')),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='артикул товара')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='скидка/старая цена товара')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='цена с учетом скидки')),
                ('quantity_stock', models.ImageField(upload_to='', verbose_name='количество на складе')),
                ('quantity_select', models.IntegerField(blank=True, null=True, verbose_name='выбор количества')),
                ('existence', models.BooleanField(blank=True, default=True, null=True, verbose_name='наличие товара на складе')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoryproductmodel', verbose_name='категория товара')),
                ('product_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.descriptionproductmodel', verbose_name='данные товара')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategoryproductmodel', verbose_name='подкатегория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ChosenProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Товар для сравнения',
                'verbose_name_plural': 'Товары для сравнения',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный товар',
                'verbose_name_plural': 'Избранные товары',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
