# Generated by Django 4.2.5 on 2023-10-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='some discription', verbose_name='описание товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categoryproductmodel', verbose_name='категория товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='скидка/старая цена товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='existence',
            field=models.BooleanField(default=True, verbose_name='наличие товара товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='foto',
            field=models.ImageField(upload_to='media', verbose_name='фото товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='наименование товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(verbose_name='фото товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity_select',
            field=models.IntegerField(blank=True, null=True, verbose_name='выбор количества'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategoryproductmodel', verbose_name='подкатегория товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='vendor_cod',
            field=models.IntegerField(verbose_name='артикул товара'),
        ),
    ]
