# Generated by Django 4.2.5 on 2023-10-10 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmodel_description_alter_productmodel_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='vendor_cod',
            new_name='article',
        ),
    ]
