# Generated by Django 4.2.5 on 2023-10-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_vendor_cod_productmodel_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='article',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='артикул товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoryproductmodel', verbose_name='категория товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='existence',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='наличие товара товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='фото товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='стоимость за единицу'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategoryproductmodel', verbose_name='подкатегория товара'),
        ),
    ]
