# Generated by Django 4.2.5 on 2023-10-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_compareproductmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compareproductmodel',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='ChosenProductModel',
        ),
        migrations.RemoveField(
            model_name='compareproductmodel',
            name='user',
        ),
    ]
