# Generated by Django 4.2.5 on 2023-10-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_compareproductmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteproductmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favoriteproductmodel',
            name='user',
        ),
    ]
