# Generated by Django 4.2.5 on 2023-10-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productmodel_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='скидка/старая цена товара'),
        ),
    ]
