# Generated by Django 4.2.5 on 2023-10-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='цена с учетом скидки'),
        ),
    ]
