# Generated by Django 4.2.5 on 2023-10-13 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_favoriteproductmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подарка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание подарка')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование акции')),
                ('sum_product', models.FloatField(verbose_name='Сумма товара в корзине')),
                ('count_person', models.PositiveIntegerField(verbose_name='количество человек воспользовавшихся акцией')),
                ('limit_person', models.PositiveIntegerField(verbose_name='Ограничение по количеству человек')),
                ('limit_discount', models.PositiveIntegerField(verbose_name='Ограничение по количеству товара')),
                ('date_end_discount', models.DateField(verbose_name='Дата окончания акции')),
                ('is_active', models.BooleanField(default=False, verbose_name='Действующая/архивная акция')),
                ('action_type', models.CharField(choices=[('discount', 'Скидка'), ('gift', 'Подарок')], max_length=20, verbose_name='Тип акции')),
                ('discount_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер скидки')),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categoryproductmodel', verbose_name='Категория товара')),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.gift', verbose_name='Подарок')),
                ('product', models.ManyToManyField(to='product.productmodel', verbose_name='товары по акции')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
