# Generated by Django 4.2.5 on 2023-10-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_gift_discountmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='discount',
        ),
    ]
