# Generated by Django 4.2.5 on 2023-10-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productmodel_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='скидка/старая цена товара'),
        ),
    ]
