# Generated by Django 4.2.5 on 2023-10-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productmodel_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='product',
            field=models.ManyToManyField(related_name='products', to='product.productmodel', verbose_name='товары по акции'),
        ),
    ]
