# Generated by Django 4.2.5 on 2023-10-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_discountmodel_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountmodel',
            old_name='limit_discount',
            new_name='limit_product',
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='count_product',
            field=models.PositiveIntegerField(default=1, verbose_name='количество человек воспользовавшихся акцией'),
            preserve_default=False,
        ),
    ]
