# Generated by Django 4.2.5 on 2023-10-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_discountmodel_count_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='count_person',
            field=models.PositiveIntegerField(default=0, verbose_name='количество человек воспользовавшихся акцией'),
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='count_product',
            field=models.PositiveIntegerField(default=0, verbose_name='количество купленных товаров по акции'),
        ),
    ]
