# Generated by Django 4.2.5 on 2023-10-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_discountmodel_count_person_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountModel',
        ),
        migrations.DeleteModel(
            name='Gift',
        ),
    ]
