# Generated by Django 4.2.5 on 2023-10-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_delete_discountmodel_delete_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(default=1000.0, verbose_name='стоимость за единицу'),
            preserve_default=False,
        ),
    ]
