# Generated by Django 4.2.5 on 2023-10-18 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_catalogmodel_remove_productmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproductmodel',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.catalogmodel'),
            preserve_default=False,
        ),
    ]
