# Generated by Django 4.2.5 on 2023-10-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_categoryproductmodel_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product_data',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.catalogmodel', verbose_name='каталог товаров'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoryproductmodel', verbose_name='категория товара'),
        ),
    ]
