# Generated by Django 4.2.5 on 2023-10-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productmodel_product_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
    ]
