# Generated by Django 4.2.5 on 2023-10-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_productmodel_catalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.subcategoryproductmodel', verbose_name='подкатегория товара'),
            preserve_default=False,
        ),
    ]
