# Generated by Django 4.2.5 on 2023-10-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_productmodel_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproductmodel',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='product.catalogmodel'),
        ),
        migrations.AlterField(
            model_name='subcategoryproductmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.categoryproductmodel'),
        ),
    ]
