# Generated by Django 4.2.5 on 2023-10-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_categoryproductmodel_catalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproductmodel',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='product.catalogmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subcategoryproductmodel', verbose_name='подкатегория товара'),
        ),
    ]
