# Generated by Django 4.2.5 on 2023-10-23 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_categoryproductmodel_catalog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='quantity_select',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='article',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена с учетом скидки'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='existence',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Наличие товара на складе'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(verbose_name='Стоимость за единицу'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.descriptionproductmodel', verbose_name='Данные товара'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity_stock',
            field=models.IntegerField(verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subcategoryproductmodel', verbose_name='Подкатегория товара'),
        ),
    ]
