# Generated by Django 4.2.5 on 2023-10-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_productmodel_quantity_select_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='opt_price',
            field=models.FloatField(blank=True, null=True, verbose_name='ОПТовая цена за единицу товара'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='opt_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество товара для ОПТа'),
        ),
    ]
