# Generated by Django 4.2.5 on 2023-10-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_productmodel_opt_price_productmodel_opt_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания товара'),
        ),
    ]
