# Generated by Django 4.2.5 on 2023-10-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_productmodel_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания товара'),
        ),
    ]
