# Generated by Django 4.2.5 on 2023-10-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_productmodel_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Товар активный/скрытый'),
        ),
    ]
