# Generated by Django 4.2.5 on 2023-10-23 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_productmodel_quantity_select_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_rename_reviewproductview_reviewproductmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproductmodel',
            name='count_stars',
            field=models.PositiveIntegerField(choices=[('1', 'One Star'), ('2', 'Two Star'), ('3', 'Three Star'), ('4', 'Four Star'), ('5', 'Five Star')], default=0, verbose_name='Количество звезд'),
        ),
        migrations.AlterField(
            model_name='reviewproductmodel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='reviewproductmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='reviewproductmodel',
            name='review_text',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='reviewproductmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
