# Generated by Django 4.2.5 on 2023-10-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='quantity_product',
            field=models.IntegerField(default=10, verbose_name='выбор количества товара'),
            preserve_default=False,
        ),
    ]
