# Generated by Django 4.2.5 on 2023-10-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartmodel_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='sum',
            new_name='sum_products',
        ),
    ]
