# Generated by Django 4.2.5 on 2023-10-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_sum_cartmodel_sum_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='total_price',
            field=models.FloatField(default=200.0, verbose_name='итоговая сумма всех товаров'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='sum_products',
            field=models.FloatField(verbose_name='сумма по товару в корзине'),
        ),
    ]
