# Generated by Django 4.2.5 on 2023-10-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_productmodel_is_active'),
        ('cart', '0005_cartmodel_total_price_alter_cartmodel_sum_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productmodel', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity_product',
            field=models.IntegerField(verbose_name='Выбор количества товара'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='sum_products',
            field=models.FloatField(verbose_name='Сумма по товару в корзине'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='total_price',
            field=models.FloatField(verbose_name='Итоговая сумма всех товаров'),
        ),
    ]
