# Generated by Django 4.2.5 on 2023-10-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPerson',
            new_name='ContactPersonModel',
        ),
    ]
