# Generated by Django 4.2.5 on 2023-10-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_contactperson_contactpersonmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndividualUserModel',
        ),
    ]
