# Generated by Django 4.2.5 on 2023-10-05 10:24

import apps.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_companyusermodel_delete_contactpersonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseusermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.user.validators.validate_phone_number]),
        ),
    ]
