# Generated by Django 4.2.5 on 2023-10-05 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_baseusermodel_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseusermodel',
            name='address',
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
