# Generated by Django 4.2.5 on 2023-10-05 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_baseusermodel_address_addressmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseusermodel',
            name='region',
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
