# Generated by Django 4.2.5 on 2023-10-05 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_baseusermodel_region_regionmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regionmodel'),
        ),
    ]
