# Generated by Django 4.2.5 on 2023-10-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_regionmodel_user_baseusermodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseusermodel',
            old_name='user',
            new_name='region',
        ),
    ]
