# Generated by Django 4.2.5 on 2023-10-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_user_baseusermodel_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='city',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='region',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
