# Generated by Django 4.2.5 on 2023-10-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_addressmodel_district_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseusermodel',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='region_kk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regionmodel'),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='region_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regionmodel'),
        ),
    ]
