# Generated by Django 4.2.5 on 2023-10-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_baseusermodel_email_kk_baseusermodel_email_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseusermodel',
            name='email_kk',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='password_kk',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='password_ru',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='phone_number_kk',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='phone_number_ru',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='username_kk',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='username_ru',
        ),
    ]
