# Generated by Django 4.2.5 on 2023-10-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_baseusermodel_email_kk_baseusermodel_email_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseusermodel',
            name='email_kk',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='region_kk',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='region_ru',
        ),
    ]
