# Generated by Django 4.2.5 on 2023-10-06 12:13

import apps.user.validators
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_baseusermodel_email_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='apartment_number_kk',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='apartment_number_ru',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='district_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='district_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='floor_kk',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='floor_ru',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='house_number_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='house_number_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='street_kk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='street_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='user_kk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='user_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='email_kk',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='email_ru',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='phone_number_kk',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.user.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='phone_number_ru',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.user.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='region_kk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regionmodel'),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='region_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regionmodel'),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='username_kk',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='username_ru',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='city_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='city_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='region_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='region_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
