# Generated by Django 4.2.5 on 2023-10-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_addressmodel_apartment_number_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseusermodel',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regionmodel'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='region_kk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regionmodel'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='region_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regionmodel'),
        ),
    ]
