# Generated by Django 4.2.5 on 2023-10-08 03:25

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_baseusermodel_region_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseusermodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='email_kk',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='email_ru',
        ),
    ]
