# Generated by Django 4.2.5 on 2023-10-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_baseusermodel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='apartment_number_kk',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='apartment_number_ru',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='floor_kk',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='floor_ru',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='house_number_kk',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='house_number_ru',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='user_kk',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='user_ru',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='phone_number_kk',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='phone_number_ru',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='username_kk',
        ),
        migrations.RemoveField(
            model_name='baseusermodel',
            name='username_ru',
        ),
    ]
