# Generated by Django 4.2.5 on 2023-10-10 06:03

import apps.user.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_addressmodel_apartment_number_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='apartment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='номер квартиры'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='district_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='district_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='этаж'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='номер дома'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='street_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='street_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.user.validators.validate_phone_number], verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regionmodel', verbose_name='место положения область/город'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='region_kk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regionmodel', verbose_name='место положения область/город'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='region_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.regionmodel', verbose_name='место положения область/город'),
        ),
    ]
