# Generated by Django 4.2.5 on 2023-10-18 13:54

import django.contrib.auth.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_addressmodel_options_alter_regionmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseusermodel',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
