# Generated by Django 4.2.5 on 2023-10-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('bronze', 'бронза'), ('silver', 'серебро'), ('gold', 'золото'), ('platinum', 'платина')], max_length=10, verbose_name='Уровень лояльности')),
                ('discount_percentage', models.PositiveSmallIntegerField(verbose_name='Процент скидки')),
                ('sum_step', models.PositiveIntegerField(verbose_name='Порог цены')),
            ],
            options={
                'verbose_name': 'Система лояльности',
                'verbose_name_plural': 'Системы лояльности',
            },
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='use_limit_loyalty',
            field=models.BooleanField(default=True, verbose_name='Учитывать систему лояльности'),
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='use_limit_person',
            field=models.BooleanField(default=True, verbose_name='Учитывать лимит по количеству человек'),
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='use_limit_product',
            field=models.BooleanField(default=True, verbose_name='Учитывать лимит по количеству товара'),
        ),
    ]
