# Generated by Django 4.2.5 on 2023-10-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_discountmodel_use_limit_sum_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountmodel',
            old_name='sum_product',
            new_name='limit_sum_product',
        ),
    ]
