# Generated by Django 4.2.5 on 2023-10-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_delete_discountmodel_delete_gift'),
        ('promotion', '0004_rename_sum_product_discountmodel_limit_sum_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productmodel', verbose_name='Подарок'),
        ),
    ]
