# Generated by Django 4.2.5 on 2023-10-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_alter_discountmodel_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='фото акции'),
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='вывод на фронт'),
        ),
    ]
