# Generated by Django 4.2.5 on 2023-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_categoryproductmodel_catalog_and_more'),
        ('promotion', '0006_discountmodel_image_discountmodel_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product.productmodel', verbose_name='товары по акции'),
        ),
    ]
