# Generated by Django 4.2.5 on 2023-10-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_categoryproductmodel_catalog_and_more'),
        ('promotion', '0007_alter_discountmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='category_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoryproductmodel', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='product',
            field=models.ManyToManyField(related_name='products', to='product.productmodel', verbose_name='товары по акции'),
        ),
    ]
