# Generated by Django 4.2.5 on 2023-10-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0009_remove_discountmodel_category_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действующая/архивная акция'),
        ),
    ]
