# Generated by Django 4.2.5 on 2023-10-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0010_alter_discountmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='discount_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Размер скидки'),
        ),
    ]
