# Generated by Django 4.2.5 on 2023-10-27 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0011_alter_discountmodel_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltymodel',
            name='discount_percentage',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Процент скидки не может быть меньше 0'), django.core.validators.MaxValueValidator(100, message='Процент скидки не может быть больше 100 ')], verbose_name='Процент скидки'),
        ),
    ]
