# Generated by Django 4.2.5 on 2023-10-16 13:21

import apps.user.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_alter_productmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='дата оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличный'), ('non_cash', 'Безналичный'), ('card', 'Оплата экварингом ')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('delivery_address', models.CharField(max_length=250, verbose_name='Адрес доставки')),
                ('contact_phone', models.CharField(max_length=20, validators=[apps.user.validators.validate_phone_number], verbose_name='Номер телефона')),
                ('status', models.CharField(blank=True, choices=[('new_paid', 'Новые заказы оплаченные'), ('new_unpaid', 'Новые заказы не оплаченные'), ('in_progress', 'Заказы в обработке'), ('completed', 'Завершенные заказы'), ('returned', 'Возврат товара')], max_length=20, null=True)),
                ('total_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общее количество')),
                ('total_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общая стоимость')),
                ('payment_manager', models.ForeignKey(blank=True, limit_choices_to={'user_permissions': 'manager_permission'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер, ответственный за оплату')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость товара с учетом количества')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productmodel', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
