# Generated by Django 4.2.5 on 2023-10-17 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_remove_order_payment_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_permissions': 'manager_permission'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер, ответственный за оплату'),
        ),
    ]
