# Generated by Django 4.2.5 on 2023-10-18 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_order_payment_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер, ответственный за оплату'),
        ),
    ]
