# Generated by Django 4.2.5 on 2023-10-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_productmodel_is_active'),
        ('order', '0006_orderitem_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='gift',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gift',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_items_gift', to='product.productmodel', verbose_name='Подарок'),
        ),
    ]
