# Generated by Django 4.2.5 on 2023-10-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_orderitem_gift_orderitem_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличный'), ('non_cash', 'Безналичный'), ('card', 'Оплата экварингом')], max_length=10, verbose_name='Метод оплаты'),
        ),
    ]
