---
version : '3.9'

services:
  db:
    container_name: ArtFoot_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ArtFoot_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 3s
      retries: 10
      interval: 3s
    networks:
      - ArtFoot

#  api:
#    container_name: api_ArtFoot
#    build:
#      dockerfile: docker/deploy/Dockerfile
#      context: ../..
#    depends_on:
#      db:
#        condition: service_healthy
#    env_file:
#      - ../../.env
#    ports:
#      - 80:80
#    networks:
#      - ArtFoot


  redis:
    container_name: redis
    image: redis
    restart: always
    env_file:
      - ../../.env
    #    environment:
    #      REDIS_HOST: ${REDIS_HOST}
    #      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6379:6379

networks:
  ArtFoot:
    driver: bridge

volumes :
  ArtFoot_pg_data:
