# Generated by Django 4.2.5 on 2023-10-05 09:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_delete_companyusermodel_delete_contactpersonmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
            },
        ),
        migrations.CreateModel(
            name='CompanyUserModel',
            fields=[
                ('baseusermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('bin_iin', models.CharField(max_length=255)),
                ('iik', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('bik', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('non_cash', 'Безналичный расчет')], default='non_cash', max_length=10)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_user.contactpersonmodel')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
            bases=('user.baseusermodel',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
