# Generated by Django 4.2.5 on 2023-10-05 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_baseusermodel_phone_number'),
        ('company_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('addressmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.addressmodel')),
            ],
            options={
                'verbose_name': 'Адрес Компании',
                'verbose_name_plural': 'Адреса компаний',
            },
            bases=('user.addressmodel',),
        ),
    ]
