# Generated by Django 4.2.5 on 2023-10-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_user', '0002_companyaddress'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companyusermodel',
            managers=[
            ],
        ),
    ]
