# Generated by Django 4.2.5 on 2023-10-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_user', '0003_alter_companyusermodel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyusermodel',
            name='bank_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='bank_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='bik_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='bik_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='bin_iin_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='bin_iin_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='company_address_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='company_address_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='company_name_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='company_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='contact_person_kk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_user.contactpersonmodel'),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='contact_person_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_user.contactpersonmodel'),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='iik_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='iik_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='payment_method_kk',
            field=models.CharField(choices=[('cash', 'Наличные'), ('non_cash', 'Безналичный расчет')], default='non_cash', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='companyusermodel',
            name='payment_method_ru',
            field=models.CharField(choices=[('cash', 'Наличные'), ('non_cash', 'Безналичный расчет')], default='non_cash', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contactpersonmodel',
            name='first_name_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactpersonmodel',
            name='first_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactpersonmodel',
            name='second_name_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactpersonmodel',
            name='second_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactpersonmodel',
            name='surname_kk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactpersonmodel',
            name='surname_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
