# Generated by Django 4.2.5 on 2023-10-08 03:25

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_user', '0004_companyusermodel_bank_kk_companyusermodel_bank_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companyusermodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
