# Generated by Django 4.2.5 on 2023-10-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_user', '0005_alter_companyusermodel_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyusermodel',
            name='bin_iin',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='bin_iin_kk',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='bin_iin_ru',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
