# Generated by Django 4.2.5 on 2023-10-08 04:35

import apps.company_user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_user', '0006_alter_companyusermodel_bin_iin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyusermodel',
            name='bin_iin',
            field=models.PositiveBigIntegerField(validators=[apps.company_user.validators.bin_iin_validator]),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='bin_iin_kk',
            field=models.PositiveBigIntegerField(null=True, validators=[apps.company_user.validators.bin_iin_validator]),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='bin_iin_ru',
            field=models.PositiveBigIntegerField(null=True, validators=[apps.company_user.validators.bin_iin_validator]),
        ),
    ]
