# Generated by Django 4.2.5 on 2023-10-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_user', '0008_alter_companyusermodel_bin_iin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyusermodel',
            name='bank_kk',
        ),
        migrations.RemoveField(
            model_name='companyusermodel',
            name='bank_ru',
        ),
        migrations.RemoveField(
            model_name='companyusermodel',
            name='bik_kk',
        ),
        migrations.RemoveField(
            model_name='companyusermodel',
            name='bik_ru',
        ),
        migrations.RemoveField(
            model_name='companyusermodel',
            name='bin_iin_kk',
        ),
        migrations.RemoveField(
            model_name='companyusermodel',
            name='bin_iin_ru',
        ),
        migrations.RemoveField(
            model_name='companyusermodel',
            name='company_name_kk',
        ),
        migrations.RemoveField(
            model_name='companyusermodel',
            name='company_name_ru',
        ),
        migrations.RemoveField(
            model_name='companyusermodel',
            name='iik_kk',
        ),
        migrations.RemoveField(
            model_name='companyusermodel',
            name='iik_ru',
        ),
        migrations.RemoveField(
            model_name='companyusermodel',
            name='payment_method_kk',
        ),
        migrations.RemoveField(
            model_name='companyusermodel',
            name='payment_method_ru',
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cache'), ('non_cash', 'Non_cash')], default='non_cash', max_length=10),
        ),
    ]
