# Generated by Django 4.2.5 on 2023-10-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_user', '0009_remove_companyusermodel_bank_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='office_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='company_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_user.companyaddress'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='company_address_kk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_user.companyaddress'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='company_address_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_user.companyaddress'),
        ),
    ]
