# Generated by Django 4.2.5 on 2023-10-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_user', '0010_companyaddress_country_companyaddress_office_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='country',
            field=models.CharField(max_length=255, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='office_number',
            field=models.PositiveSmallIntegerField(verbose_name='номер офиса'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='bank',
            field=models.CharField(max_length=255, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='bik',
            field=models.CharField(max_length=255, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='bin_iin',
            field=models.PositiveBigIntegerField(verbose_name='БИН/ИИН'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='company_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_user.companyaddress', verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='company_address_kk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_user.companyaddress', verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='company_address_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_user.companyaddress', verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='название компании'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_user.contactpersonmodel', verbose_name='контактное лицо'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='contact_person_kk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_user.contactpersonmodel', verbose_name='контактное лицо'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='contact_person_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_user.contactpersonmodel', verbose_name='контактное лицо'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='iik',
            field=models.CharField(max_length=255, verbose_name='ИИК'),
        ),
        migrations.AlterField(
            model_name='companyusermodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cache'), ('non_cash', 'Non_cash')], default='non_cash', max_length=10, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='contactpersonmodel',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='contactpersonmodel',
            name='first_name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='contactpersonmodel',
            name='first_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='contactpersonmodel',
            name='second_name',
            field=models.CharField(max_length=255, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='contactpersonmodel',
            name='second_name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='contactpersonmodel',
            name='second_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='contactpersonmodel',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='contactpersonmodel',
            name='surname_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='contactpersonmodel',
            name='surname_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='фамилия'),
        ),
    ]
