# Generated by Django 4.2.5 on 2023-10-17 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_alter_discountmodel_gift'),
        ('company_user', '0011_alter_companyaddress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyusermodel',
            name='loyalty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promotion.loyaltymodel', verbose_name='Уровень системы лояльности'),
            preserve_default=False,
        ),
    ]
