# Generated by Django 4.2.5 on 2023-10-17 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_alter_discountmodel_gift'),
        ('company_user', '0012_companyusermodel_loyalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyusermodel',
            name='loyalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion.loyaltymodel', verbose_name='Уровень системы лояльности'),
        ),
    ]
