# Generated by Django 4.2.5 on 2023-10-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_user', '0013_alter_companyusermodel_loyalty'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companyusermodel',
            managers=[
            ],
        ),
    ]
